GET http://localhost:8080/users

POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Idea User",
  "lastName": "Idea User lastname",
  "email": "user@jetbrains.com",
  "password": "1234"
}